<a href="https://colab.research.google.com/github/Jasmine-Syed/Deep-Learning/blob/main/sklearn_MLPClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd


In [3]:
##  Import the dataset, and add header columns with the names function

data = pd.read_csv("wine.csv",names=('Type', 'Alcohol', 'Malic', 'Ash', 
                      'Alcalinity', 'Magnesium', 'Phenols', 
                      'Flavanoids', 'Nonflavanoids',
                      'Proanthocyanins', 'Color', 'Hue', 
                      'Dilution', 'Proline'))



In [4]:
#Check out the data
print("shape",data.shape)


shape (178, 14)


In [5]:
data.head(4)


Type  Alcohol  Malic   Ash  ...  Color   Hue  Dilution  Proline
0     1    14.23   1.71  2.43  ...   5.64  1.04      3.92     1065
1     1    13.20   1.78  2.14  ...   4.38  1.05      3.40     1050
2     1    13.16   2.36  2.67  ...   5.68  1.03      3.17     1185
3     1    14.37   1.95  2.50  ...   7.80  0.86      3.45     1480

[4 rows x 14 columns]

In [6]:
Y = data.Type
X = data.drop('Type', axis=1)

In [18]:

#Split your data into training and testing sets using SciKit Learn's train_test_split function from model_selection
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=5)
x_train.shape,y_train.shape,x_test.shape,y_test.shape





((142, 13), (142,), (36, 13), (36,))

In [19]:
#use the built in standers scalar for standardisation
from sklearn.preprocessing import StandardScaler
scalar= StandardScaler()
x_train_scale = scalar.fit_transform(x_train)
x_test_scale = scalar.transform(x_test)





In [20]:
#Train your model using Scikit Learn’s estimator objects
# In this step, we will build the neural network model using the scikit-learn library's estimator object, 'Multi-Layer Perceptron Classifier'. 
# The first line of code (shown below) imports 'MLPClassifier'.

from sklearn.neural_network import MLPClassifier


In [21]:
#Create an instance of the model by defining the hidden_layer_sizes

net = MLPClassifier((8,8,6),'relu',max_iter=1000,solver='lbfgs')



In [11]:
print(net)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(6, 8, 6), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)


In [22]:
#Fit the training data to your model

model = net.fit(x_train_scale,y_train)


In [14]:
# Extract the MLP weights and biases after training your model
print(model.coefs_)


[array([[-0.02820755,  0.75361386, -0.44774315, -0.82308599,  0.79234969,
        -1.17078207],
       [ 0.29467699,  0.49531173,  1.20550297,  0.64776653, -0.23672323,
        -0.44874673],
       [ 0.10246871, -0.22274779, -0.0400729 , -0.75142356,  0.06107952,
        -0.92310041],
       [ 0.88297409, -1.59062508,  0.8866406 , -0.17897662, -0.98974946,
         1.0435987 ],
       [-0.41978752, -0.35686449,  0.37547078, -2.05153029,  0.06728524,
         0.55134158],
       [-1.10380116,  0.04710034, -1.01734396, -1.06701139,  0.93242938,
        -0.35680756],
       [-0.73224171,  0.21101106, -0.61394129, -0.35613057,  0.48029016,
         0.11440706],
       [ 0.07463915, -0.41092902, -0.84634035,  0.02840576, -1.16058375,
        -0.65334436],
       [-0.52218383, -0.37876581, -0.52333937,  0.54494393,  1.22243693,
         0.59756198],
       [ 1.72713919, -0.21381021,  0.52027415,  0.61349521,  0.37510341,
        -0.74601168],
       [-1.32649847, -0.19111811, -1.45957047, -0

In [15]:
model.intercepts_

[array([0.0049173 , 0.28873022, 0.51400182, 1.52616499, 0.27355421,
        1.0227858 ]),
 array([-0.26871504,  0.81485315, -0.35335398,  0.15676448,  0.49043243,
        -0.23430976,  0.73708006, -0.30039924]),
 array([-0.41905595, -0.30637631, -0.59600343, -0.84001538,  0.13865194,
         0.14900287]),
 array([ 0.78491486,  6.96555276, -7.81915507])]

In [23]:
#Use predict () method to get predictions

y_test_predict=net.predict(x_test_scale)


In [24]:
#Use SciKit-Learn's built in metrics to evaluate how well our model performed

from sklearn import metrics
model_acc = metrics.accuracy_score(y_test,y_test_predict)
model_acc

0.9722222222222222

In [25]:
# Saving the model:

import pickle
filename = "wine.h5"
pickle.dump(net, open(filename, 'wb'))


In [26]:
load_net_model =pickle.load(open("wine.h5", 'rb'))

In [27]:
load_net_model

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(6, 8, 6), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)